#!/bin/bash

alias cd="cd -P"
alias back='cd "$OLDPWD"'
alias wifioff='networksetup -setairportpower en0 off'
alias wifion='networksetup -setairportpower en0 on'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gdc='git diff --cached'
alias gco='git checkout'

alias pg='ping google.com'
alias d='date'
alias batt='pmset -g batt'

alias ll='ls -lh'
alias la='ls -a'
alias lla='ls -lha'

alias tmux='tmux -2'

