#!/bin/zsh

alias cd='cd -P'
alias back='cd "$OLDPWD"'
alias "cd.."='cd ..'
alias dot='cd $HOME/dotfiles'
alias play='cd $HOME/Desktop'

alias pg='ping google.com'
alias d='date'

alias g='git'
alias gs='git status'
alias gst='git stash'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gdc='git diff --cached'

alias ll='ls -lFh'
alias la='ls -alhF'

alias tmux='tmux -2'

eval $(thefuck --alias)

mach=$HOME/dotfiles/machines/"$(hostname)"/alias

if [[ -f "$mach" ]]; then source $mach; fi
