#!/bin/zsh

alias cd='cd -P'
alias back='cd "$OLDPWD"'
alias work='cd ~/.projects'
alias "cd.."='cd ..'

alias wifioff='networksetup -setairportpower en0 off'
alias wifion='networksetup -setairportpower en0 on'
alias pg='ping google.com'
alias d='date'
alias batt='pmset -g batt'

alias wifioff='networksetup -setairportpower en0 off'
alias wifion='networksetup -setairportpower en0 on'

alias g='git'
alias gs='git status'
alias gst='git stash'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gdc='git diff --cached'

alias ll='ls -lFh'
alias la='ls -aF'
alias lla='ls -lFha'

alias tmux='tmux -2'

