cask_args appdir: "/Applications"

brew "asciinema"
brew "bat"
brew "go"
brew "dep"
brew "exa"
brew "fd"
brew "fzf"
brew "git"
brew "python"
brew "grip"
brew "htop"
brew "neovim"
brew "ripgrep"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "zsh"

brew "sashaweiss/projects/itree"
brew "getantibody/tap/antibody"

cask "1password"
cask "iterm2"
cask "alfred"
cask "bartender"
cask "contexts"
cask "daisydisk"
cask "firefox"
cask "google-chrome"
cask "postman"
cask "private-internet-access"
cask "spectacle"
cask "amphetamine"

brew "mas"

mas "Amphetamine", id: 937984704
