cask_args appdir: "/Applications"

tap "dandavison/delta", "https://github.com/dandavison/delta"

brew "asdf"
brew "bat"
brew "exa"
brew "fd"
brew "fzf"
brew "git"
brew "git-delta"
brew "gpg"
brew "grip"
brew "htop"
brew "hyperfine"
brew "neovim"
brew "ripgrep"
brew "tmux"
brew "tree"
brew "wget"
brew "zsh"

brew "sashaweiss/projects/itree"

cask "alacritty"
cask "1password"
cask "iterm2"
cask "alfred"
cask "bartender"
cask "contexts"
cask "daisydisk"
cask "firefox"
cask "google-chrome"
cask "postman"
cask "private-internet-access"
cask "spectacle"
cask "visual-studio-code"

brew "mas"

mas "Amphetamine", id: 937984704
