#!/usr/bin/env zsh

# Arguments behave weirdly here, in that the `git log` command will error with
# "ambiguous argument" if you pass an empty string (i.e., by always passing
# arguments to it, but then invoking the script without arguments).
#
# To work around this, manually check for arguments and run the command
# differently as needed.

local format_string='%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)'
local git_command='git log --graph --abbrev-commit --decorate --format=format:"$format_string"'

if [ "$#" -eq 0 ]; then
  eval "$git_command"
else
  eval "$git_command $@"
fi
