#!/usr/bin/env bash

declare -a extensions=(
  "equinusocio.vsc-material-theme"
  "esbenp.prettier-vscode"
  "mariomatheu.syntax-project-pbxproj"
  "mrmlnc.vscode-scss"
  "pkief.material-icon-theme"
  "twxs.cmake"
  "vscodevim.vim"
)

for extension in "${extensions[@]}"; do
  code --install-extension "$extension"
done
