#!/usr/bin/env bash

declare -a extensions=(
  "equinusocio.vsc-material-theme"
  "equinusocio.vsc-material-theme-icons"
  "esbenp.prettier-vscode"
  "pkief.material-icon-theme"
  "vscodevim.vim"
)

for extension in "${extensions[@]}"; do
  code --install-extension "$extension"
done
