#!/bin/zsh

# Get all the path stuff online, since this is run from a non-interactive shell
source ~/.zshrc

# Install P0 tools
./brew/install.sh && source ~/.zshrc
./git/install.sh && source ~/.zshrc
./vim/install.sh && source ~/.zshrc
./tmux/install.sh && source ~/.zshrc

# Install languages
./python/install.sh && source ~/.zshrc
./node/install.sh && source ~/.zshrc
./go/install.sh && source ~/.zshrc

# Install CLI utilities
brew install fzf wget tree fd ripgrep && source ~/.zshrc

# Install vim plugins
vim +PlugInstall +qa
vim +GoInstallBinaries +qa
