#!/bin/zsh

ln -s $DOTFILES/git/gitconfig ~/.gitconfig
ln -s $DOTFILES/git/gitignore ~/.gitignore

mkdir ~/.ssh
ln -s $DOTFILES/ssh/config ~/.ssh/config

ln -s $DOTFILES/vim/vimrc ~/.vimrc

ln -s ~/.vim ~/.config/nvim
ln -s ~/.vimrc ~/.config/nvim/init.vim

ln -s $DOTFILES/tmux/tmux.conf ~/.tmux.conf

ln -s $DOTFILES/zsh/zshrc ~/.zshrc
