#!/usr/bin/env zsh

ln -fs "$DOTFILES/git/gitconfig" "$HOME/.gitconfig"
ln -fs "$DOTFILES/git/gitignore" "$HOME/.gitignore"

ln -fs "$DOTFILES/vim/vimrc" "$HOME/.vimrc"
ln -fs "$DOTFILES/vim/xvimrc" "$HOME/.xvimrc"

mkdir "$HOME/.vim"
mkdir "$HOME/.config"
ln -Fs "$HOME/.vim $HOME/.config/nvim"
ln -Fs "$HOME/.vimrc $HOME/.config/nvim/init.vim"
ln -Fs "$DOTFILES/vim/plugins/coc.json" "$HOME/.config/nvim/coc-settings.json"

ln -fs "$DOTFILES/tmux/tmux.conf" "$HOME/.tmux.conf"

ln -fs "$DOTFILES/zsh/zshrc" "$HOME/.zshrc"

mkdir -p "$HOME/.config/alacritty"
ln -fs "$DOTFILES/alacritty/alacritty.yml" "$HOME/.config/alacritty/alacritty.yml"
