#!/bin/zsh

ln -s ~/dotfiles/git/gitconfig ~/.gitconfig
ln -s ~/dotfiles/git/gitignore ~/.gitignore

mkdir ~/.ssh
ln -s ~/dotfiles/ssh/config ~/.ssh/config

ln -s ~/dotfiles/vim/vimrc ~/.vimrc

ln -s ~/.vim ~/.config/nvim
ln -s ~/.vimrc ~/.config/nvim/init.vim

ln -s ~/dotfiles/tmux/tmux.conf ~/.tmux.conf

ln -s ~/dotfiles/zsh/zshrc ~/.zshrc
