#!/usr/bin/env bash

if ! command -v asdf > /dev/null; then
  echo "asdf is not installed!"
  exit 1
fi

asdf plugin-list | grep -q nodejs || asdf plugin-add nodejs
asdf plugin-list | grep -q python || asdf plugin-add python
asdf plugin-list | grep -q ruby || asdf plugin-add ruby

# install whatever tools are listed in "$HOME/.tool-versions"
cd "$HOME" && asdf install
