#!/usr/bin/env zsh

usage () {
  echo "Usage:
  sync-keybindings <to|from>
  "
  return 1
}

if [ "$#" -ne 1 ]; then
  echo "Wrong number of arguments!\n"
  usage
  return 1
fi

KB_FILE="sasha.idekeybindings"
LOCAL_KB_DIR="$DOTFILES/xcode"
REMOTE_KB_DIR="$HOME/Library/Developer/Xcode/UserData/KeyBindings"

if [[ "$1" == "to" ]]; then
  mkdir -p "$REMOTE_KB_DIR"

  cp "$LOCAL_KB_DIR/$KB_FILE" "$REMOTE_KB_DIR"
elif [[ "$1" == "from" ]]; then
  cp "$REMOTE_KB_DIR/$KB_FILE" "$LOCAL_KB_DIR"
else
  echo "Unrecognized argument!\n"
  usage
  return 1
fi
