#!/usr/bin/env zsh

export DOTFILES="$HOME/.files"
export HOSTNAME="$(hostname)"
export BREW_PREFIX="/opt/homebrew"

export DESK="$HOME/Desktop"
export DOWN="$HOME/Downloads"
export WORK="$HOME/dev"
mkdir -p "$WORK"

export ICLOUD="$HOME/iCloud"
export OBSIDIAN="$HOME/Library/Mobile Documents/iCloud~md~obsidian/Documents"
