#!/usr/bin/env zsh

export DOTFILES="$HOME/.files"

# See: https://geoff.greer.fm/lscolors
export CLICOLOR=1
export LSCOLORS="GxgxcxdxCxegedabagacad"
export LS_COLORS='di=1;34:ln=36:so=32:pi=33:ex=1;32:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43'

export HOSTNAME="$(hostname)"
