# Shortcut to this dotfiles path is $DOTFILES
export DOTFILES=$HOME/dotfiles

# Load helper scripts
if [ -z "$OLD_PATH" ]; then
  OLD_PATH=$PATH
  export OLD_PATH
fi

PATH="$DOTFILES/script:$OLD_PATH"
export PATH



# Get all zsh files
typeset -U config_files
config_files=($DOTFILES/**/*.zsh)

# Load the path files
for file in ${(M)config_files:#*/path.zsh}
do
  source $file
done

# Load everything but the path files
for file in ${${config_files:#*/path.zsh}}
do
  source $file
done

autoload -U compinit
compinit

unset config_files
unsetopt AUTO_CD
