# If ever you want to profile the shell:
# https://htr3n.github.io/2018/07/faster-zsh/

source "$DOTFILES/zsh/android.zsh"
source "$DOTFILES/zsh/asdf.zsh"
source "$DOTFILES/zsh/cargo.zsh"
source "$DOTFILES/zsh/completion.zsh"
source "$DOTFILES/zsh/fzf/fzf.zsh"
source "$DOTFILES/zsh/fzf/git.zsh"
source "$DOTFILES/zsh/keymap.zsh"
source "$DOTFILES/zsh/plugins.zsh"
source "$DOTFILES/zsh/prompt.zsh"
source "$DOTFILES/zsh/settings.zsh"
source "$DOTFILES/zsh/vscode.zsh"

# Note: no quotes below to get proper expansion
for alias in $DOTFILES/zsh/alias/*.zsh; do
  source $alias
done
