# If ever you want to profile the shell:
# https://htr3n.github.io/2018/07/faster-zsh/

source "$DOTFILES/zsh/completion.zsh"
source "$DOTFILES/zsh/functions.zsh"
source "$DOTFILES/zsh/keymap.zsh"
source "$DOTFILES/zsh/plugins.zsh"
source "$DOTFILES/zsh/prompt.zsh"
source "$DOTFILES/zsh/settings.zsh"

source "$DOTFILES/zsh/alias/*.zsh"
source "$DOTFILES/zsh/fzf/*.zsh"

source "$DOTFILES/zsh/path.zsh"
