#!/usr/bin/env bash

if ! command -v brew > /dev/null; then
  curl -fsSL "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"

  if ./zsh/functions/is_mac; then
    export PATH="/usr/local/bin":$PATH
  else
    export PATH="/home/linuxbrew/.linuxbrew/bin":$PATH
  fi
fi

brew bundle --file "./util/brew/Brewfile"
